Add single spring-plugin-core dependency to pom.xml, exclude spring-plugin-core from all usdot jpo-ode modules. No longer getting classPath error, however, the following error is now present: Error creating bean with name 'halLinkDisocoverer' defined in class path resource [org/springframework/hateoas/mediatype/hal/HalMediaTypeConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.hateoas.client.LinkDiscoverer]: Factory method 'halLinkDisocoverer' threw exception; nested exception is java.lang.NoClassDefFoundError: com/jayway/jsonpath/PathNotFoundException